DataJukebox_helpExpression:
  path: '/DataJukebox/Help/Expression'
  defaults: { _controller: 'DataJukeboxBundle:DataJukeboxHelp:helpExpression' }

DataJukebox_helpFilter:
  path: '/DataJukebox/Help/Filter'
  defaults: { _controller: 'DataJukeboxBundle:DataJukeboxHelp:helpFilter' }
