# DataJukeboxBundle\Resources\config\services.yml
services:
  DataJukebox:
    class: DataJukeboxBundle\Service
    arguments: ['@doctrine']

  # DataJukebox.doctrine.event_listener:
  #   class: DataJukeboxBundle\DoctrineEventListener
  #   arguments: ['@security.token_storage']
  #   tags:
  #     - { name: doctrine.event_listener, event: onFlush }

  DataJukebox.twig.extension:
    class: DataJukeboxBundle\TwigExtension
    tags:
      - { name: twig.extension }

  DataJukebox.form.type_extension:
    class: DataJukeboxBundle\FormTypeExtension
    tags:
      - { name: form.type_extension, alias: form, extended_type: Symfony\Component\Form\AbstractType }
